INSERT INTO classes(type_id, title, equipment, course_id) VALUES 
(1, 'Практика 1', 'screen tablet camera', 1);
(2, 'Лекция 1', 'camera whiteboard microscope', 1);
(1, 'Практика 2', 'whiteboard whiteboard', 1);
(2, 'Лекция 2', 'camera laptop', 1);
(1, 'Практика 3', 'projector', 1);
(2, 'Лекция 3', 'camera camera', 1);
(1, 'Практика 4', 'projector projector', 1);
(2, 'Лекция 4', 'camera laptop', 1);
(1, 'Практика 5', 'microphone microphone', 1);
(2, 'Лекция 5', 'whiteboard server camera', 1);
(1, 'Практика 6', 'screen camera', 1);
(2, 'Лекция 6', 'projector', 1);
(1, 'Практика 7', 'laptop screen speakers', 1);
(2, 'Лекция 7', 'laptop', 1);
(1, 'Практика 8', 'whiteboard screen screen', 1);
(2, 'Лекция 8', 'microscope', 1);
(1, 'Практика 1', 'projector', 2);
(2, 'Лекция 1', 'sensors microscope whiteboard', 2);
(1, 'Практика 2', 'camera', 2);
(2, 'Лекция 2', 'projector', 2);
(1, 'Практика 3', 'laptop projector whiteboard', 2);
(2, 'Лекция 3', 'projector projector', 2);
(1, 'Практика 4', 'speakers tablet', 2);
(2, 'Лекция 4', 'laptop whiteboard tools', 2);
(1, 'Практика 5', 'projector', 2);
(2, 'Лекция 5', 'sensors', 2);
(1, 'Практика 6', 'whiteboard laptop', 2);
(2, 'Лекция 6', 'camera whiteboard camera', 2);
(1, 'Практика 7', 'projector tablet speakers', 2);
(2, 'Лекция 7', 'camera', 2);
(1, 'Практика 8', 'speakers speakers', 2);
(2, 'Лекция 8', 'laptop', 2);
(1, 'Практика 1', 'whiteboard laptop', 3);
(2, 'Лекция 1', 'microscope server', 3);
(1, 'Практика 2', 'projector laptop', 3);
(2, 'Лекция 2', 'tools sensors server', 3);
(1, 'Практика 3', 'screen whiteboard', 3);
(2, 'Лекция 3', 'whiteboard', 3);
(1, 'Практика 4', 'screen', 3);
(2, 'Лекция 4', 'sensors', 3);
(1, 'Практика 5', 'speakers laptop', 3);
(2, 'Лекция 5', 'projector sensors', 3);
(1, 'Практика 6', 'camera projector', 3);
(2, 'Лекция 6', 'server sensors whiteboard', 3);
(1, 'Практика 7', 'laptop whiteboard whiteboard', 3);
(2, 'Лекция 7', 'laptop', 3);
(1, 'Практика 8', 'whiteboard', 3);
(2, 'Лекция 8', 'whiteboard microscope', 3);
(1, 'Практика 1', 'speakers', 4);
(2, 'Лекция 1', 'microscope sensors tools', 4);
(1, 'Практика 2', 'laptop whiteboard', 4);
(2, 'Лекция 2', 'sensors sensors', 4);
(1, 'Практика 3', 'camera camera tablet', 4);
(2, 'Лекция 3', 'laptop projector', 4);
(1, 'Практика 4', 'whiteboard laptop tablet', 4);
(2, 'Лекция 4', 'whiteboard', 4);
(1, 'Практика 5', 'camera screen speakers', 4);
(2, 'Лекция 5', 'sensors', 4);
(1, 'Практика 6', 'microphone speakers', 4);
(2, 'Лекция 6', 'tools projector', 4);
(1, 'Практика 7', 'microphone', 4);
(2, 'Лекция 7', 'whiteboard camera', 4);
(1, 'Практика 8', 'screen microphone camera', 4);
(2, 'Лекция 8', 'projector microscope', 4);
(1, 'Практика 1', 'screen microphone', 5);
(2, 'Лекция 1', 'tools sensors sensors', 5);
(1, 'Практика 2', 'tablet', 5);
(2, 'Лекция 2', 'camera laptop', 5);
(1, 'Практика 3', 'whiteboard camera speakers', 5);
(2, 'Лекция 3', 'whiteboard sensors sensors', 5);
(1, 'Практика 4', 'tablet speakers screen', 5);
(2, 'Лекция 4', 'tools laptop camera', 5);
(1, 'Практика 5', 'camera', 5);
(2, 'Лекция 5', 'server laptop', 5);
(1, 'Практика 6', 'speakers', 5);
(2, 'Лекция 6', 'camera projector', 5);
(1, 'Практика 7', 'camera whiteboard', 5);
(2, 'Лекция 7', 'tools whiteboard sensors', 5);
(1, 'Практика 8', 'laptop microphone speakers', 5);
(2, 'Лекция 8', 'server camera', 5);
(1, 'Практика 1', 'screen speakers screen', 6);
(2, 'Лекция 1', 'tools whiteboard laptop', 6);
(1, 'Практика 2', 'screen', 6);
(2, 'Лекция 2', 'whiteboard tools laptop', 6);
(1, 'Практика 3', 'projector', 6);
(2, 'Лекция 3', 'whiteboard laptop laptop', 6);
(1, 'Практика 4', 'screen laptop tablet', 6);
(2, 'Лекция 4', 'camera tools', 6);
(1, 'Практика 5', 'whiteboard camera projector', 6);
(2, 'Лекция 5', 'server', 6);
(1, 'Практика 6', 'microphone microphone laptop', 6);
(2, 'Лекция 6', 'camera whiteboard', 6);
(1, 'Практика 7', 'tablet tablet', 6);
(2, 'Лекция 7', 'camera', 6);
(1, 'Практика 8', 'whiteboard', 6);
(2, 'Лекция 8', 'server sensors tools', 6);
(1, 'Практика 1', 'whiteboard screen laptop', 7);
(2, 'Лекция 1', 'server microscope server', 7);
(1, 'Практика 2', 'whiteboard screen', 7);
(2, 'Лекция 2', 'tools tools tools', 7);
(1, 'Практика 3', 'laptop screen speakers', 7);
(2, 'Лекция 3', 'server', 7);
(1, 'Практика 4', 'camera whiteboard laptop', 7);
(2, 'Лекция 4', 'microscope camera', 7);
(1, 'Практика 5', 'microphone', 7);
(2, 'Лекция 5', 'camera whiteboard microscope', 7);
(1, 'Практика 6', 'laptop', 7);
(2, 'Лекция 6', 'camera', 7);
(1, 'Практика 7', 'tablet microphone', 7);
(2, 'Лекция 7', 'whiteboard projector', 7);
(1, 'Практика 8', 'microphone microphone', 7);
(2, 'Лекция 8', 'projector', 7);
(1, 'Практика 1', 'camera whiteboard screen', 8);
(2, 'Лекция 1', 'sensors laptop camera', 8);
(1, 'Практика 2', 'screen projector whiteboard', 8);
(2, 'Лекция 2', 'whiteboard', 8);
(1, 'Практика 3', 'microphone', 8);
(2, 'Лекция 3', 'microscope server server', 8);
(1, 'Практика 4', 'microphone', 8);
(2, 'Лекция 4', 'microscope', 8);
(1, 'Практика 5', 'projector', 8);
(2, 'Лекция 5', 'microscope', 8);
(1, 'Практика 6', 'projector whiteboard', 8);
(2, 'Лекция 6', 'sensors sensors whiteboard', 8);
(1, 'Практика 7', 'screen tablet laptop', 8);
(2, 'Лекция 7', 'server laptop', 8);
(1, 'Практика 8', 'microphone tablet camera', 8);
(2, 'Лекция 8', 'whiteboard', 8);
(1, 'Практика 1', 'laptop whiteboard', 9);
(2, 'Лекция 1', 'projector', 9);
(1, 'Практика 2', 'screen projector speakers', 9);
(2, 'Лекция 2', 'whiteboard sensors', 9);
(1, 'Практика 3', 'projector projector', 9);
(2, 'Лекция 3', 'sensors camera', 9);
(1, 'Практика 4', 'projector', 9);
(2, 'Лекция 4', 'tools', 9);
(1, 'Практика 5', 'laptop', 9);
(2, 'Лекция 5', 'whiteboard server', 9);
(1, 'Практика 6', 'projector', 9);
(2, 'Лекция 6', 'server', 9);
(1, 'Практика 7', 'projector screen laptop', 9);
(2, 'Лекция 7', 'projector', 9);
(1, 'Практика 8', 'screen', 9);
(2, 'Лекция 8', 'projector camera', 9);
(1, 'Практика 1', 'screen projector tablet', 10);
(2, 'Лекция 1', 'camera tools microscope', 10);
(1, 'Практика 2', 'speakers camera', 10);
(2, 'Лекция 2', 'server laptop whiteboard', 10);
(1, 'Практика 3', 'whiteboard speakers laptop', 10);
(2, 'Лекция 3', 'tools', 10);
(1, 'Практика 4', 'screen microphone', 10);
(2, 'Лекция 4', 'sensors sensors laptop', 10);
(1, 'Практика 5', 'speakers', 10);
(2, 'Лекция 5', 'camera', 10);
(1, 'Практика 6', 'whiteboard speakers speakers', 10);
(2, 'Лекция 6', 'whiteboard server', 10);
(1, 'Практика 7', 'microphone whiteboard laptop', 10);
(2, 'Лекция 7', 'laptop microscope', 10);
(1, 'Практика 8', 'laptop speakers', 10);
(2, 'Лекция 8', 'tools camera server', 10);
(1, 'Практика 1', 'microphone projector projector', 11);
(2, 'Лекция 1', 'tools camera server', 11);
(1, 'Практика 2', 'whiteboard', 11);
(2, 'Лекция 2', 'server', 11);
(1, 'Практика 3', 'whiteboard camera microphone', 11);
(2, 'Лекция 3', 'sensors', 11);
(1, 'Практика 4', 'projector camera', 11);
(2, 'Лекция 4', 'laptop', 11);
(1, 'Практика 5', 'screen whiteboard microphone', 11);
(2, 'Лекция 5', 'tools', 11);
(1, 'Практика 6', 'laptop', 11);
(2, 'Лекция 6', 'server projector camera', 11);
(1, 'Практика 7', 'screen', 11);
(2, 'Лекция 7', 'camera microscope projector', 11);
(1, 'Практика 8', 'projector tablet microphone', 11);
(2, 'Лекция 8', 'laptop server', 11);
(1, 'Практика 1', 'tablet projector', 12);
(2, 'Лекция 1', 'sensors', 12);
(1, 'Практика 2', 'microphone', 12);
(2, 'Лекция 2', 'camera', 12);
(1, 'Практика 3', 'laptop tablet tablet', 12);
(2, 'Лекция 3', 'sensors server whiteboard', 12);
(1, 'Практика 4', 'projector whiteboard', 12);
(2, 'Лекция 4', 'server whiteboard', 12);
(1, 'Практика 5', 'microphone', 12);
(2, 'Лекция 5', 'laptop', 12);
(1, 'Практика 6', 'projector', 12);
(2, 'Лекция 6', 'tools', 12);
(1, 'Практика 7', 'whiteboard', 12);
(2, 'Лекция 7', 'tools laptop laptop', 12);
(1, 'Практика 8', 'projector microphone', 12);
(2, 'Лекция 8', 'laptop server', 12);
(1, 'Практика 1', 'screen', 13);
(2, 'Лекция 1', 'sensors camera', 13);
(1, 'Практика 2', 'screen laptop speakers', 13);
(2, 'Лекция 2', 'whiteboard', 13);
(1, 'Практика 3', 'screen screen', 13);
(2, 'Лекция 3', 'microscope microscope', 13);
(1, 'Практика 4', 'tablet whiteboard laptop', 13);
(2, 'Лекция 4', 'laptop whiteboard tools', 13);
(1, 'Практика 5', 'projector camera microphone', 13);
(2, 'Лекция 5', 'camera', 13);
(1, 'Практика 6', 'laptop screen', 13);
(2, 'Лекция 6', 'server', 13);
(1, 'Практика 7', 'whiteboard', 13);
(2, 'Лекция 7', 'whiteboard', 13);
(1, 'Практика 8', 'microphone microphone projector', 13);
(2, 'Лекция 8', 'laptop whiteboard', 13);
(1, 'Практика 1', 'screen speakers tablet', 14);
(2, 'Лекция 1', 'tools', 14);
(1, 'Практика 2', 'projector tablet', 14);
(2, 'Лекция 2', 'sensors', 14);
(1, 'Практика 3', 'whiteboard', 14);
(2, 'Лекция 3', 'camera server', 14);
(1, 'Практика 4', 'laptop speakers', 14);
(2, 'Лекция 4', 'projector', 14);
(1, 'Практика 5', 'laptop camera', 14);
(2, 'Лекция 5', 'microscope microscope tools', 14);
(1, 'Практика 6', 'tablet tablet camera', 14);
(2, 'Лекция 6', 'server', 14);
(1, 'Практика 7', 'speakers speakers', 14);
(2, 'Лекция 7', 'laptop camera whiteboard', 14);
(1, 'Практика 8', 'microphone projector', 14);
(2, 'Лекция 8', 'sensors laptop', 14);
(1, 'Практика 1', 'screen laptop projector', 15);
(2, 'Лекция 1', 'sensors tools', 15);
(1, 'Практика 2', 'screen', 15);
(2, 'Лекция 2', 'laptop camera', 15);
(1, 'Практика 3', 'speakers laptop camera', 15);
(2, 'Лекция 3', 'microscope sensors', 15);
(1, 'Практика 4', 'camera screen', 15);
(2, 'Лекция 4', 'sensors laptop', 15);
(1, 'Практика 5', 'screen speakers camera', 15);
(2, 'Лекция 5', 'tools server server', 15);
(1, 'Практика 6', 'microphone', 15);
(2, 'Лекция 6', 'camera server projector', 15);
(1, 'Практика 7', 'projector camera', 15);
(2, 'Лекция 7', 'camera tools sensors', 15);
(1, 'Практика 8', 'tablet projector', 15);
(2, 'Лекция 8', 'whiteboard microscope sensors', 15);
(1, 'Практика 1', 'camera screen whiteboard', 16);
(2, 'Лекция 1', 'laptop projector', 16);
(1, 'Практика 2', 'projector camera screen', 16);
(2, 'Лекция 2', 'laptop', 16);
(1, 'Практика 3', 'whiteboard', 16);
(2, 'Лекция 3', 'tools laptop camera', 16);
(1, 'Практика 4', 'screen microphone', 16);
(2, 'Лекция 4', 'laptop laptop server', 16);
(1, 'Практика 5', 'screen', 16);
(2, 'Лекция 5', 'microscope', 16);
(1, 'Практика 6', 'screen projector camera', 16);
(2, 'Лекция 6', 'laptop sensors tools', 16);
(1, 'Практика 7', 'screen speakers laptop', 16);
(2, 'Лекция 7', 'tools', 16);
(1, 'Практика 8', 'microphone microphone projector', 16);
(2, 'Лекция 8', 'server microscope', 16);
(1, 'Практика 1', 'tablet projector tablet', 17);
(2, 'Лекция 1', 'microscope camera sensors', 17);
(1, 'Практика 2', 'whiteboard projector screen', 17);
(2, 'Лекция 2', 'microscope', 17);
(1, 'Практика 3', 'camera', 17);
(2, 'Лекция 3', 'sensors tools', 17);
(1, 'Практика 4', 'screen camera', 17);
(2, 'Лекция 4', 'tools', 17);
(1, 'Практика 5', 'screen speakers camera', 17);
(2, 'Лекция 5', 'server', 17);
(1, 'Практика 6', 'screen whiteboard speakers', 17);
(2, 'Лекция 6', 'whiteboard whiteboard tools', 17);
(1, 'Практика 7', 'whiteboard screen speakers', 17);
(2, 'Лекция 7', 'camera', 17);
(1, 'Практика 8', 'screen camera screen', 17);
(2, 'Лекция 8', 'sensors sensors whiteboard', 17);
(1, 'Практика 1', 'tablet', 18);
(2, 'Лекция 1', 'tools laptop', 18);
(1, 'Практика 2', 'camera', 18);
(2, 'Лекция 2', 'laptop camera server', 18);
(1, 'Практика 3', 'laptop microphone', 18);
(2, 'Лекция 3', 'sensors', 18);
(1, 'Практика 4', 'projector tablet', 18);
(2, 'Лекция 4', 'microscope server microscope', 18);
(1, 'Практика 5', 'laptop', 18);
(2, 'Лекция 5', 'sensors tools', 18);
(1, 'Практика 6', 'whiteboard whiteboard', 18);
(2, 'Лекция 6', 'whiteboard laptop', 18);
(1, 'Практика 7', 'screen camera projector', 18);
(2, 'Лекция 7', 'camera', 18);
(1, 'Практика 8', 'microphone whiteboard', 18);
(2, 'Лекция 8', 'server camera laptop', 18);
(1, 'Практика 1', 'whiteboard camera speakers', 19);
(2, 'Лекция 1', 'tools projector', 19);
(1, 'Практика 2', 'laptop laptop camera', 19);
(2, 'Лекция 2', 'laptop', 19);
(1, 'Практика 3', 'camera', 19);
(2, 'Лекция 3', 'tools whiteboard', 19);
(1, 'Практика 4', 'laptop projector laptop', 19);
(2, 'Лекция 4', 'camera tools', 19);
(1, 'Практика 5', 'laptop whiteboard microphone', 19);
(2, 'Лекция 5', 'camera sensors', 19);
(1, 'Практика 6', 'microphone screen tablet', 19);
(2, 'Лекция 6', 'camera server server', 19);
(1, 'Практика 7', 'tablet microphone tablet', 19);
(2, 'Лекция 7', 'laptop microscope', 19);
(1, 'Практика 8', 'speakers', 19);
(2, 'Лекция 8', 'server server sensors', 19);
(1, 'Практика 1', 'whiteboard tablet camera', 20);
(2, 'Лекция 1', 'camera laptop server', 20);
(1, 'Практика 2', 'whiteboard projector', 20);
(2, 'Лекция 2', 'laptop server sensors', 20);
(1, 'Практика 3', 'microphone', 20);
(2, 'Лекция 3', 'server server laptop', 20);
(1, 'Практика 4', 'whiteboard', 20);
(2, 'Лекция 4', 'laptop whiteboard', 20);
(1, 'Практика 5', 'speakers', 20);
(2, 'Лекция 5', 'projector microscope microscope', 20);
(1, 'Практика 6', 'screen camera', 20);
(2, 'Лекция 6', 'whiteboard', 20);
(1, 'Практика 7', 'screen screen', 20);
(2, 'Лекция 7', 'whiteboard server', 20);
(1, 'Практика 8', 'microphone', 20);
(2, 'Лекция 8', 'tools whiteboard', 20);
(1, 'Практика 1', 'camera projector camera', 21);
(2, 'Лекция 1', 'microscope', 21);
(1, 'Практика 2', 'whiteboard', 21);
(2, 'Лекция 2', 'tools laptop laptop', 21);
(1, 'Практика 3', 'screen', 21);
(2, 'Лекция 3', 'projector server', 21);
(1, 'Практика 4', 'screen camera', 21);
(2, 'Лекция 4', 'projector sensors server', 21);
(1, 'Практика 5', 'microphone', 21);
(2, 'Лекция 5', 'microscope', 21);
(1, 'Практика 6', 'whiteboard', 21);
(2, 'Лекция 6', 'server camera sensors', 21);
(1, 'Практика 7', 'speakers speakers', 21);
(2, 'Лекция 7', 'whiteboard', 21);
(1, 'Практика 8', 'camera camera', 21);
(2, 'Лекция 8', 'laptop whiteboard whiteboard', 21);
(1, 'Практика 1', 'camera', 22);
(2, 'Лекция 1', 'tools', 22);
(1, 'Практика 2', 'camera camera speakers', 22);
(2, 'Лекция 2', 'laptop projector laptop', 22);
(1, 'Практика 3', 'laptop', 22);
(2, 'Лекция 3', 'camera whiteboard', 22);
(1, 'Практика 4', 'laptop camera projector', 22);
(2, 'Лекция 4', 'whiteboard tools camera', 22);
(1, 'Практика 5', 'tablet', 22);
(2, 'Лекция 5', 'whiteboard', 22);
(1, 'Практика 6', 'whiteboard', 22);
(2, 'Лекция 6', 'whiteboard', 22);
(1, 'Практика 7', 'laptop screen', 22);
(2, 'Лекция 7', 'sensors server', 22);
(1, 'Практика 8', 'projector screen camera', 22);
(2, 'Лекция 8', 'camera', 22);
(1, 'Практика 1', 'camera', 23);
(2, 'Лекция 1', 'server sensors microscope', 23);
(1, 'Практика 2', 'screen', 23);
(2, 'Лекция 2', 'microscope', 23);
(1, 'Практика 3', 'microphone', 23);
(2, 'Лекция 3', 'server tools camera', 23);
(1, 'Практика 4', 'tablet speakers screen', 23);
(2, 'Лекция 4', 'laptop sensors', 23);
(1, 'Практика 5', 'whiteboard', 23);
(2, 'Лекция 5', 'server', 23);
(1, 'Практика 6', 'screen', 23);
(2, 'Лекция 6', 'sensors whiteboard', 23);
(1, 'Практика 7', 'laptop projector whiteboard', 23);
(2, 'Лекция 7', 'sensors', 23);
(1, 'Практика 8', 'screen camera', 23);
(2, 'Лекция 8', 'projector tools', 23);
(1, 'Практика 1', 'microphone laptop camera', 24);
(2, 'Лекция 1', 'sensors camera', 24);
(1, 'Практика 2', 'camera projector projector', 24);
(2, 'Лекция 2', 'sensors sensors', 24);
(1, 'Практика 3', 'whiteboard screen', 24);
(2, 'Лекция 3', 'camera sensors', 24);
(1, 'Практика 4', 'laptop microphone speakers', 24);
(2, 'Лекция 4', 'server', 24);
(1, 'Практика 5', 'microphone screen', 24);
(2, 'Лекция 5', 'server whiteboard camera', 24);
(1, 'Практика 6', 'tablet whiteboard', 24);
(2, 'Лекция 6', 'projector microscope server', 24);
(1, 'Практика 7', 'projector', 24);
(2, 'Лекция 7', 'microscope sensors camera', 24);
(1, 'Практика 8', 'projector screen', 24);
(2, 'Лекция 8', 'tools', 24);
(1, 'Практика 1', 'projector speakers', 25);
(2, 'Лекция 1', 'whiteboard laptop', 25);
(1, 'Практика 2', 'camera', 25);
(2, 'Лекция 2', 'projector microscope whiteboard', 25);
(1, 'Практика 3', 'whiteboard tablet', 25);
(2, 'Лекция 3', 'server', 25);
(1, 'Практика 4', 'speakers laptop tablet', 25);
(2, 'Лекция 4', 'whiteboard', 25);
(1, 'Практика 5', 'speakers', 25);
(2, 'Лекция 5', 'whiteboard whiteboard projector', 25);
(1, 'Практика 6', 'whiteboard', 25);
(2, 'Лекция 6', 'projector projector', 25);
(1, 'Практика 7', 'screen speakers projector', 25);
(2, 'Лекция 7', 'microscope projector projector', 25);
(1, 'Практика 8', 'camera speakers speakers', 25);
(2, 'Лекция 8', 'microscope', 25);
(1, 'Практика 1', 'speakers tablet', 26);
(2, 'Лекция 1', 'whiteboard microscope server', 26);
(1, 'Практика 2', 'microphone', 26);
(2, 'Лекция 2', 'camera laptop', 26);
(1, 'Практика 3', 'tablet microphone', 26);
(2, 'Лекция 3', 'laptop whiteboard laptop', 26);
(1, 'Практика 4', 'projector speakers laptop', 26);
(2, 'Лекция 4', 'tools', 26);
(1, 'Практика 5', 'tablet laptop microphone', 26);
(2, 'Лекция 5', 'sensors sensors server', 26);
(1, 'Практика 6', 'projector', 26);
(2, 'Лекция 6', 'laptop', 26);
(1, 'Практика 7', 'screen', 26);
(2, 'Лекция 7', 'projector', 26);
(1, 'Практика 8', 'whiteboard', 26);
(2, 'Лекция 8', 'microscope tools camera', 26);
(1, 'Практика 1', 'whiteboard projector whiteboard', 27);
(2, 'Лекция 1', 'microscope', 27);
(1, 'Практика 2', 'laptop whiteboard', 27);
(2, 'Лекция 2', 'whiteboard tools', 27);
(1, 'Практика 3', 'speakers camera microphone', 27);
(2, 'Лекция 3', 'microscope whiteboard microscope', 27);
(1, 'Практика 4', 'microphone laptop', 27);
(2, 'Лекция 4', 'sensors projector laptop', 27);
(1, 'Практика 5', 'tablet microphone', 27);
(2, 'Лекция 5', 'server whiteboard whiteboard', 27);
(1, 'Практика 6', 'screen', 27);
(2, 'Лекция 6', 'whiteboard', 27);
(1, 'Практика 7', 'microphone', 27);
(2, 'Лекция 7', 'tools projector whiteboard', 27);
(1, 'Практика 8', 'speakers tablet projector', 27);
(2, 'Лекция 8', 'camera server tools', 27);
(1, 'Практика 1', 'projector projector', 28);
(2, 'Лекция 1', 'laptop', 28);
(1, 'Практика 2', 'speakers', 28);
(2, 'Лекция 2', 'projector server camera', 28);
(1, 'Практика 3', 'screen projector projector', 28);
(2, 'Лекция 3', 'camera sensors whiteboard', 28);
(1, 'Практика 4', 'laptop camera projector', 28);
(2, 'Лекция 4', 'laptop whiteboard projector', 28);
(1, 'Практика 5', 'laptop speakers camera', 28);
(2, 'Лекция 5', 'whiteboard sensors whiteboard', 28);
(1, 'Практика 6', 'screen', 28);
(2, 'Лекция 6', 'projector', 28);
(1, 'Практика 7', 'microphone', 28);
(2, 'Лекция 7', 'microscope server', 28);
(1, 'Практика 8', 'camera tablet', 28);
(2, 'Лекция 8', 'laptop', 28);
(1, 'Практика 1', 'tablet screen', 29);
(2, 'Лекция 1', 'laptop laptop', 29);
(1, 'Практика 2', 'microphone laptop', 29);
(2, 'Лекция 2', 'microscope tools', 29);
(1, 'Практика 3', 'tablet speakers tablet', 29);
(2, 'Лекция 3', 'microscope camera server', 29);
(1, 'Практика 4', 'microphone tablet', 29);
(2, 'Лекция 4', 'microscope camera', 29);
(1, 'Практика 5', 'camera laptop speakers', 29);
(2, 'Лекция 5', 'laptop whiteboard', 29);
(1, 'Практика 6', 'projector laptop', 29);
(2, 'Лекция 6', 'tools whiteboard projector', 29);
(1, 'Практика 7', 'screen', 29);
(2, 'Лекция 7', 'server', 29);
(1, 'Практика 8', 'laptop microphone', 29);
(2, 'Лекция 8', 'laptop', 29);
(1, 'Практика 1', 'camera whiteboard microphone', 30);
(2, 'Лекция 1', 'projector projector', 30);
(1, 'Практика 2', 'laptop speakers', 30);
(2, 'Лекция 2', 'whiteboard', 30);
(1, 'Практика 3', 'speakers screen whiteboard', 30);
(2, 'Лекция 3', 'laptop', 30);
(1, 'Практика 4', 'whiteboard projector', 30);
(2, 'Лекция 4', 'projector laptop', 30);
(1, 'Практика 5', 'speakers projector speakers', 30);
(2, 'Лекция 5', 'camera laptop', 30);
(1, 'Практика 6', 'screen speakers laptop', 30);
(2, 'Лекция 6', 'laptop', 30);
(1, 'Практика 7', 'tablet', 30);
(2, 'Лекция 7', 'whiteboard camera server', 30);
(1, 'Практика 8', 'camera speakers', 30);
(2, 'Лекция 8', 'tools laptop', 30);
(1, 'Практика 1', 'whiteboard speakers camera', 31);
(2, 'Лекция 1', 'server', 31);
(1, 'Практика 2', 'laptop camera', 31);
(2, 'Лекция 2', 'server server', 31);
(1, 'Практика 3', 'screen whiteboard whiteboard', 31);
(2, 'Лекция 3', 'sensors', 31);
(1, 'Практика 4', 'laptop screen microphone', 31);
(2, 'Лекция 4', 'sensors whiteboard sensors', 31);
(1, 'Практика 5', 'whiteboard', 31);
(2, 'Лекция 5', 'whiteboard whiteboard tools', 31);
(1, 'Практика 6', 'speakers speakers camera', 31);
(2, 'Лекция 6', 'sensors', 31);
(1, 'Практика 7', 'speakers microphone camera', 31);
(2, 'Лекция 7', 'microscope', 31);
(1, 'Практика 8', 'speakers', 31);
(2, 'Лекция 8', 'projector server server', 31);
(1, 'Практика 1', 'tablet tablet', 32);
(2, 'Лекция 1', 'projector sensors', 32);
(1, 'Практика 2', 'camera', 32);
(2, 'Лекция 2', 'tools microscope', 32);
(1, 'Практика 3', 'microphone screen', 32);
(2, 'Лекция 3', 'laptop camera', 32);
(1, 'Практика 4', 'screen', 32);
(2, 'Лекция 4', 'server camera', 32);
(1, 'Практика 5', 'laptop camera', 32);
(2, 'Лекция 5', 'server', 32);
(1, 'Практика 6', 'screen', 32);
(2, 'Лекция 6', 'tools server', 32);
(1, 'Практика 7', 'speakers', 32);
(2, 'Лекция 7', 'microscope tools laptop', 32);
(1, 'Практика 8', 'whiteboard', 32);
(2, 'Лекция 8', 'tools camera tools', 32);
(1, 'Практика 1', 'speakers', 33);
(2, 'Лекция 1', 'microscope microscope', 33);
(1, 'Практика 2', 'whiteboard speakers whiteboard', 33);
(2, 'Лекция 2', 'tools server', 33);
(1, 'Практика 3', 'projector', 33);
(2, 'Лекция 3', 'projector microscope laptop', 33);
(1, 'Практика 4', 'tablet', 33);
(2, 'Лекция 4', 'whiteboard camera server', 33);
(1, 'Практика 5', 'microphone speakers whiteboard', 33);
(2, 'Лекция 5', 'sensors', 33);
(1, 'Практика 6', 'microphone microphone speakers', 33);
(2, 'Лекция 6', 'whiteboard laptop tools', 33);
(1, 'Практика 7', 'whiteboard', 33);
(2, 'Лекция 7', 'camera camera server', 33);
(1, 'Практика 8', 'camera projector camera', 33);
(2, 'Лекция 8', 'whiteboard', 33);
(1, 'Практика 1', 'microphone screen', 34);
(2, 'Лекция 1', 'sensors', 34);
(1, 'Практика 2', 'camera', 34);
(2, 'Лекция 2', 'tools projector sensors', 34);
(1, 'Практика 3', 'whiteboard tablet', 34);
(2, 'Лекция 3', 'sensors sensors laptop', 34);
(1, 'Практика 4', 'laptop projector microphone', 34);
(2, 'Лекция 4', 'server sensors projector', 34);
(1, 'Практика 5', 'microphone', 34);
(2, 'Лекция 5', 'tools', 34);
(1, 'Практика 6', 'microphone projector whiteboard', 34);
(2, 'Лекция 6', 'sensors microscope laptop', 34);
(1, 'Практика 7', 'speakers projector', 34);
(2, 'Лекция 7', 'sensors server', 34);
(1, 'Практика 8', 'camera', 34);
(2, 'Лекция 8', 'laptop server projector', 34);
(1, 'Практика 1', 'projector microphone', 35);
(2, 'Лекция 1', 'microscope laptop', 35);
(1, 'Практика 2', 'laptop tablet camera', 35);
(2, 'Лекция 2', 'tools', 35);
(1, 'Практика 3', 'tablet camera speakers', 35);
(2, 'Лекция 3', 'projector projector', 35);
(1, 'Практика 4', 'projector laptop whiteboard', 35);
(2, 'Лекция 4', 'microscope camera', 35);
(1, 'Практика 5', 'speakers screen projector', 35);
(2, 'Лекция 5', 'microscope whiteboard projector', 35);
(1, 'Практика 6', 'tablet', 35);
(2, 'Лекция 6', 'camera', 35);
(1, 'Практика 7', 'microphone microphone', 35);
(2, 'Лекция 7', 'camera whiteboard', 35);
(1, 'Практика 8', 'projector speakers', 35);
(2, 'Лекция 8', 'projector tools', 35);
(1, 'Практика 1', 'microphone', 36);
(2, 'Лекция 1', 'whiteboard server', 36);
(1, 'Практика 2', 'whiteboard', 36);
(2, 'Лекция 2', 'laptop', 36);
(1, 'Практика 3', 'screen', 36);
(2, 'Лекция 3', 'server', 36);
(1, 'Практика 4', 'tablet tablet camera', 36);
(2, 'Лекция 4', 'whiteboard', 36);
(1, 'Практика 5', 'tablet whiteboard speakers', 36);
(2, 'Лекция 5', 'camera sensors', 36);
(1, 'Практика 6', 'camera laptop', 36);
(2, 'Лекция 6', 'laptop server tools', 36);
(1, 'Практика 7', 'laptop camera laptop', 36);
(2, 'Лекция 7', 'projector camera whiteboard', 36);
(1, 'Практика 8', 'screen microphone projector', 36);
(2, 'Лекция 8', 'server whiteboard', 36);
(1, 'Практика 1', 'camera projector speakers', 37);
(2, 'Лекция 1', 'tools laptop sensors', 37);
(1, 'Практика 2', 'whiteboard screen', 37);
(2, 'Лекция 2', 'laptop', 37);
(1, 'Практика 3', 'speakers camera projector', 37);
(2, 'Лекция 3', 'camera laptop camera', 37);
(1, 'Практика 4', 'tablet', 37);
(2, 'Лекция 4', 'projector whiteboard sensors', 37);
(1, 'Практика 5', 'whiteboard screen', 37);
(2, 'Лекция 5', 'sensors microscope sensors', 37);
(1, 'Практика 6', 'whiteboard speakers projector', 37);
(2, 'Лекция 6', 'camera', 37);
(1, 'Практика 7', 'laptop screen', 37);
(2, 'Лекция 7', 'tools sensors', 37);
(1, 'Практика 8', 'tablet whiteboard', 37);
(2, 'Лекция 8', 'camera microscope sensors', 37);
(1, 'Практика 1', 'whiteboard whiteboard', 38);
(2, 'Лекция 1', 'microscope', 38);
(1, 'Практика 2', 'speakers screen', 38);
(2, 'Лекция 2', 'microscope tools', 38);
(1, 'Практика 3', 'laptop', 38);
(2, 'Лекция 3', 'tools server', 38);
(1, 'Практика 4', 'screen microphone', 38);
(2, 'Лекция 4', 'projector projector camera', 38);
(1, 'Практика 5', 'projector microphone projector', 38);
(2, 'Лекция 5', 'tools camera laptop', 38);
(1, 'Практика 6', 'screen speakers screen', 38);
(2, 'Лекция 6', 'laptop laptop tools', 38);
(1, 'Практика 7', 'microphone microphone', 38);
(2, 'Лекция 7', 'microscope sensors', 38);
(1, 'Практика 8', 'screen camera whiteboard', 38);
(2, 'Лекция 8', 'sensors sensors sensors', 38);
(1, 'Практика 1', 'camera projector microphone', 39);
(2, 'Лекция 1', 'server laptop', 39);
(1, 'Практика 2', 'whiteboard', 39);
(2, 'Лекция 2', 'sensors', 39);
(1, 'Практика 3', 'screen laptop', 39);
(2, 'Лекция 3', 'server tools projector', 39);
(1, 'Практика 4', 'screen', 39);
(2, 'Лекция 4', 'laptop microscope sensors', 39);
(1, 'Практика 5', 'camera laptop', 39);
(2, 'Лекция 5', 'tools sensors sensors', 39);
(1, 'Практика 6', 'tablet', 39);
(2, 'Лекция 6', 'whiteboard projector', 39);
(1, 'Практика 7', 'tablet screen', 39);
(2, 'Лекция 7', 'laptop laptop', 39);
(1, 'Практика 8', 'microphone', 39);
(2, 'Лекция 8', 'sensors', 39);
(1, 'Практика 1', 'speakers laptop tablet', 40);
(2, 'Лекция 1', 'laptop laptop projector', 40);
(1, 'Практика 2', 'camera speakers', 40);
(2, 'Лекция 2', 'tools', 40);
(1, 'Практика 3', 'laptop', 40);
(2, 'Лекция 3', 'projector server', 40);
(1, 'Практика 4', 'laptop laptop', 40);
(2, 'Лекция 4', 'laptop sensors', 40);
(1, 'Практика 5', 'camera speakers', 40);
(2, 'Лекция 5', 'laptop projector sensors', 40);
(1, 'Практика 6', 'camera camera microphone', 40);
(2, 'Лекция 6', 'whiteboard', 40);
(1, 'Практика 7', 'whiteboard', 40);
(2, 'Лекция 7', 'projector', 40);
(1, 'Практика 8', 'projector projector', 40);
(2, 'Лекция 8', 'camera', 40);
(1, 'Практика 1', 'speakers laptop laptop', 41);
(2, 'Лекция 1', 'microscope', 41);
(1, 'Практика 2', 'speakers', 41);
(2, 'Лекция 2', 'sensors tools microscope', 41);
(1, 'Практика 3', 'projector laptop camera', 41);
(2, 'Лекция 3', 'server microscope', 41);
(1, 'Практика 4', 'speakers screen', 41);
(2, 'Лекция 4', 'projector whiteboard', 41);
(1, 'Практика 5', 'camera', 41);
(2, 'Лекция 5', 'server whiteboard', 41);
(1, 'Практика 6', 'microphone microphone laptop', 41);
(2, 'Лекция 6', 'laptop', 41);
(1, 'Практика 7', 'tablet', 41);
(2, 'Лекция 7', 'whiteboard', 41);
(1, 'Практика 8', 'projector', 41);
(2, 'Лекция 8', 'whiteboard', 41);
(1, 'Практика 1', 'whiteboard', 42);
(2, 'Лекция 1', 'whiteboard', 42);
(1, 'Практика 2', 'microphone', 42);
(2, 'Лекция 2', 'laptop tools', 42);
(1, 'Практика 3', 'laptop', 42);
(2, 'Лекция 3', 'sensors sensors projector', 42);
(1, 'Практика 4', 'microphone', 42);
(2, 'Лекция 4', 'camera whiteboard tools', 42);
(1, 'Практика 5', 'tablet projector', 42);
(2, 'Лекция 5', 'whiteboard sensors projector', 42);
(1, 'Практика 6', 'projector', 42);
(2, 'Лекция 6', 'microscope sensors tools', 42);
(1, 'Практика 7', 'projector', 42);
(2, 'Лекция 7', 'microscope', 42);
(1, 'Практика 8', 'camera', 42);
(2, 'Лекция 8', 'projector', 42);
(1, 'Практика 1', 'screen laptop', 43);
(2, 'Лекция 1', 'server', 43);
(1, 'Практика 2', 'screen camera tablet', 43);
(2, 'Лекция 2', 'laptop sensors', 43);
(1, 'Практика 3', 'screen screen microphone', 43);
(2, 'Лекция 3', 'tools', 43);
(1, 'Практика 4', 'speakers', 43);
(2, 'Лекция 4', 'microscope microscope', 43);
(1, 'Практика 5', 'camera', 43);
(2, 'Лекция 5', 'whiteboard', 43);
(1, 'Практика 6', 'camera whiteboard', 43);
(2, 'Лекция 6', 'microscope sensors', 43);
(1, 'Практика 7', 'projector camera laptop', 43);
(2, 'Лекция 7', 'whiteboard laptop', 43);
(1, 'Практика 8', 'screen', 43);
(2, 'Лекция 8', 'sensors', 43);
(1, 'Практика 1', 'whiteboard', 44);
(2, 'Лекция 1', 'sensors', 44);
(1, 'Практика 2', 'whiteboard speakers whiteboard', 44);
(2, 'Лекция 2', 'whiteboard whiteboard', 44);
(1, 'Практика 3', 'microphone screen', 44);
(2, 'Лекция 3', 'whiteboard projector', 44);
(1, 'Практика 4', 'microphone laptop', 44);
(2, 'Лекция 4', 'projector server server', 44);
(1, 'Практика 5', 'speakers whiteboard', 44);
(2, 'Лекция 5', 'laptop projector', 44);
(1, 'Практика 6', 'whiteboard', 44);
(2, 'Лекция 6', 'server', 44);
(1, 'Практика 7', 'screen', 44);
(2, 'Лекция 7', 'tools', 44);
(1, 'Практика 8', 'whiteboard', 44);
(2, 'Лекция 8', 'server sensors', 44);
(1, 'Практика 1', 'tablet speakers', 45);
(2, 'Лекция 1', 'microscope', 45);
(1, 'Практика 2', 'laptop', 45);
(2, 'Лекция 2', 'sensors server laptop', 45);
(1, 'Практика 3', 'microphone microphone speakers', 45);
(2, 'Лекция 3', 'camera', 45);
(1, 'Практика 4', 'tablet', 45);
(2, 'Лекция 4', 'projector server', 45);
(1, 'Практика 5', 'screen', 45);
(2, 'Лекция 5', 'server', 45);
(1, 'Практика 6', 'speakers camera', 45);
(2, 'Лекция 6', 'camera sensors', 45);
(1, 'Практика 7', 'whiteboard speakers laptop', 45);
(2, 'Лекция 7', 'projector whiteboard server', 45);
(1, 'Практика 8', 'microphone', 45);
(2, 'Лекция 8', 'server sensors', 45);
(1, 'Практика 1', 'projector tablet tablet', 46);
(2, 'Лекция 1', 'microscope server', 46);
(1, 'Практика 2', 'screen camera', 46);
(2, 'Лекция 2', 'tools server server', 46);
(1, 'Практика 3', 'tablet speakers tablet', 46);
(2, 'Лекция 3', 'tools', 46);
(1, 'Практика 4', 'speakers', 46);
(2, 'Лекция 4', 'laptop microscope', 46);
(1, 'Практика 5', 'screen tablet projector', 46);
(2, 'Лекция 5', 'laptop', 46);
(1, 'Практика 6', 'tablet microphone', 46);
(2, 'Лекция 6', 'camera tools', 46);
(1, 'Практика 7', 'projector', 46);
(2, 'Лекция 7', 'camera', 46);
(1, 'Практика 8', 'whiteboard screen', 46);
(2, 'Лекция 8', 'whiteboard', 46);
(1, 'Практика 1', 'whiteboard', 47);
(2, 'Лекция 1', 'laptop whiteboard camera', 47);
(1, 'Практика 2', 'projector screen', 47);
(2, 'Лекция 2', 'whiteboard tools', 47);
(1, 'Практика 3', 'whiteboard tablet', 47);
(2, 'Лекция 3', 'sensors', 47);
(1, 'Практика 4', 'whiteboard', 47);
(2, 'Лекция 4', 'sensors laptop', 47);
(1, 'Практика 5', 'tablet screen', 47);
(2, 'Лекция 5', 'sensors', 47);
(1, 'Практика 6', 'laptop laptop microphone', 47);
(2, 'Лекция 6', 'laptop', 47);
(1, 'Практика 7', 'projector', 47);
(2, 'Лекция 7', 'sensors camera', 47);
(1, 'Практика 8', 'projector', 47);
(2, 'Лекция 8', 'server server laptop', 47);
(1, 'Практика 1', 'speakers tablet', 48);
(2, 'Лекция 1', 'whiteboard server tools', 48);
(1, 'Практика 2', 'laptop', 48);
(2, 'Лекция 2', 'projector', 48);
(1, 'Практика 3', 'speakers tablet screen', 48);
(2, 'Лекция 3', 'tools projector', 48);
(1, 'Практика 4', 'speakers', 48);
(2, 'Лекция 4', 'camera tools', 48);
(1, 'Практика 5', 'projector', 48);
(2, 'Лекция 5', 'whiteboard tools', 48);
(1, 'Практика 6', 'projector camera tablet', 48);
(2, 'Лекция 6', 'whiteboard whiteboard sensors', 48);
(1, 'Практика 7', 'screen', 48);
(2, 'Лекция 7', 'server', 48);
(1, 'Практика 8', 'camera camera', 48);
(2, 'Лекция 8', 'sensors tools', 48);
